@enum BackendType DOCKER NATIVE

"""
    detect_backend() → BackendType

macOS → DOCKER (OpenFOAM runs inside Docker container),
Linux → NATIVE (OpenFOAM installed natively).
"""
function detect_backend()
    Sys.isapple() ? DOCKER : NATIVE
end

const DOCKER_CONTAINER = "openfoam2412"
const DOCKER_MOUNT_HOST = joinpath(homedir(), "OpenFOAM", "cases")
const DOCKER_MOUNT_CONTAINER = "/home/openfoam"

"""
    docker_case_path(host_path) → String

Translate a host path like `~/OpenFOAM/cases/airPower/...`
to the container path `/home/openfoam/airPower/...`.
"""
function docker_case_path(host_path::AbstractString)
    abs = abspath(host_path)
    if !startswith(abs, DOCKER_MOUNT_HOST)
        error("Path $abs is not under $DOCKER_MOUNT_HOST — cannot map to Docker container")
    end
    rel = abs[length(DOCKER_MOUNT_HOST)+2:end]
    return joinpath(DOCKER_MOUNT_CONTAINER, rel)
end

"""
    foam_exec(backend, case_path, cmd; verbose=true) → Bool

Run a single OpenFOAM command in `case_path`.
Returns true if the command succeeded.
"""
function foam_exec(backend::BackendType, case_path::AbstractString, cmd::AbstractString; verbose::Bool=true)
    if backend == DOCKER
        container_path = docker_case_path(case_path)
        full_cmd = `docker exec $(DOCKER_CONTAINER) bash -c "source /openfoam/bash.rc && cd $(container_path) && $(cmd)"`
    else
        full_cmd = `bash -c "cd $(abspath(case_path)) && source /usr/lib/openfoam/openfoam2412/etc/bashrc && $(cmd)"`
    end
    verbose && @info "Running: $cmd" case=basename(case_path)
    proc = run(ignorestatus(full_cmd), wait=true)
    if proc.exitcode != 0
        @error "Command failed (exit $(proc.exitcode)): $cmd"
        return false
    end
    return true
end

"""
    foam_script(backend, case_path, script; verbose=true) → Bool

Run an existing shell script (e.g. `run`, `clean`, `runPostProcess`) inside the case.
"""
function foam_script(backend::BackendType, case_path::AbstractString, script::AbstractString,
                     args::AbstractString=""; verbose::Bool=true)
    script_path = joinpath(case_path, script)
    if !isfile(script_path)
        @warn "Script not found: $script_path"
        return false
    end
    cmd = isempty(args) ? "bash $script" : "bash $script $args"
    foam_exec(backend, case_path, cmd; verbose)
end

"""
    write_flat_plate_input_param(case_dir)

Generate `constant/inputParam` for the FlatPlateModule from the central
Julia inputs.  The file is auto-generated and should not be edited by hand.
"""
function write_flat_plate_input_param(case_dir::AbstractString)
    p = inp.DFP
    path = joinpath(case_dir, "constant", "inputParam")
    mkpath(dirname(path))
    open(path, "w") do io
        println(io, """/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                 |
| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\\\    /   O peration     | Version:  v2312                                 |
|   \\\\  /    A nd           | Website:  www.openfoam.com                      |
|    \\\\/     M anipulation  |                                                 |
\\*---------------------------------------------------------------------------*/
// AUTO-GENERATED by airPower orchestrator (inputs.jl) — do not edit
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      inputParam;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

//Boundaries information
Upinlet
{
//Inflow parameters
 Uinf        $(p.Uinf);
 Winf        $(p.Winf);
 xInlet      $(p.xInlet);

//Top-boundary parameters (coefficient of polinomyal, Casacuberta et al, 2022)
 pa4         $(p.pa4);
 pa3         $(p.pa3);
 pa2         $(p.pa2);
 pa1         $(p.pa1);
 pa0         $(p.pa0);

//Fluid properties
 freeStreamViscosity   $(p.freeStreamViscosity);

//Output settings
 outputFormat          $(p.outputFormat);
}

// ************************************************************************* //""")
    end
    @info "Generated constant/inputParam" case=basename(case_dir)
end

const FOAM_HEADER = """/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                 |
| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\\\    /   O peration     | Version:  v2312                                 |
|   \\\\  /    A nd           | Website:  www.openfoam.com                      |
|    \\\\/     M anipulation  |                                                 |
\\*---------------------------------------------------------------------------*/
// AUTO-GENERATED by airPower orchestrator (inputs.jl) — do not edit"""

"""
    write_tunnel_input_param(case_dir)

Generate `constant/inputParam` for TunnelCase from the central Julia inputs.
"""
function write_tunnel_input_param(case_dir::AbstractString)
    f = inp.TTCP.flow
    t = inp.TTCP.tunnel
    path = joinpath(case_dir, "constant", "inputParam")
    mkpath(dirname(path))
    open(path, "w") do io
        println(io, """$(FOAM_HEADER)
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      inputParam;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

flowParam
{
//1.- Tunnel Geometrical Parameters

 //Basic geometry

 tunnelInletHeight     $(t.tunnelInletHeight);        // [mm] (tunnel half height)

 tunnelOutletHeight    $(t.tunnelOutletHeight);        // [mm]

 flatPlateLength       $(t.flatPlateLength);         //[mm]

 z0                    $(t.z0);          // first z-plane [mm]
 z1                     $(t.z1);          // second z-plane [mm]  (quasi-2D thickness)

 // Secondary geometrical parameters

 seleAR                $(t.seleAR);            // [-]

 seleHalfThickness     $(t.seleHalfThickness);           // [mm]

 lamTurbHeight         $(t.lamTurbHeight);           // [mm]

//2.- Grid Discretization Parameters

 //Streamwise partitions
 Nx $(t.Nx);                             // [-]

 //Wall-normal partitions
 Ny $(t.Ny);                              // [-]

//3.- Flow Parameters (m as dimensional units)

 freeStreamVelocity    $(f.freeStreamVelocity);       //[ms^1]

 freeStreamViscosity   $(f.freeStreamViscosity);    //[m^2s^1]

//4.- Turbulence Parameters

 turbulenceIntensity   $(t.turbulenceIntensity);        //[-]
 turbLengthScale       $(t.turbLengthScale);         //[m]

//5.- BSpline Control Points

 xcp1 $(t.xcp1);
 ycp1 $(t.ycp1);

 xcp2 $(t.xcp2);
 ycp2 $(t.ycp2);

 xcp3 $(t.xcp3);
 ycp3 $(t.ycp3);
}

// ************************************************************************* //""")
    end
    @info "Generated constant/inputParam" case=basename(case_dir)
end

"""
    write_airfoil_le_input_param(case_dir)

Generate `constant/inputParam` for AirfoilLECase from the central Julia inputs.
(Grid/domain parameters in `system/inputDomain` are no longer needed —
 `generateGrid.jl` reads `inputs.jl` directly.)
"""
function write_airfoil_le_input_param(case_dir::AbstractString)
    f = inp.TTCP.flow
    a = inp.TTCP.airfoilLE

    # ── constant/inputParam ──────────────────────────────────────────────
    path_ip = joinpath(case_dir, "constant", "inputParam")
    mkpath(dirname(path_ip))
    open(path_ip, "w") do io
        println(io, """$(FOAM_HEADER)
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      inputParam;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

//Boundaries information
Upinlet
{
//Fluid properties
 freeStreamViscosity   $(f.freeStreamViscosity);         //[m^2s^1]

//Output settings
 outputFormat          $(a.outputFormat);      // csv | binary

//Export region settings
 exportMode            $(a.exportMode);  // full | partial
 xiInlet               $(a.xiInlet);     // chord fraction for inlet boundary (x/c)
 xiOutlet              $(a.xiOutlet);     // chord fraction for outlet boundary (x/c)
 exportHeight          $(a.exportHeight);       // wall-normal distance from surface [mm]

//Airfoil geometry
 chord                 $(f.chord);      // [mm]
 alphaDeg              $(f.alphaDeg);     // [deg]
 xCenter               $(f.xCenter);     // [mm]
 yCenter               $(f.yCenter);     // [mm]
}

// ************************************************************************* //""")
    end
    @info "Generated constant/inputParam" case=basename(case_dir)
end

"""
    run_julia_subprocess(script_path; dir, args) → Bool

Run a Julia script as a subprocess (isolated from our module scope).
"""
function run_julia_subprocess(script_path::AbstractString;
                              dir::AbstractString=dirname(script_path),
                              args::Vector{String}=String[])
    abs_script = abspath(script_path)
    if !isfile(abs_script)
        @warn "Julia script not found: $abs_script"
        return false
    end
    @info "Running Julia subprocess: $(basename(abs_script))"
    cmd = `julia $abs_script $args`
    proc = run(Cmd(cmd; dir), wait=true)
    return proc.exitcode == 0
end
