using Printf

@enum BackendType DOCKER NATIVE

"""
    detect_backend() → BackendType

macOS → DOCKER (OpenFOAM runs inside Docker container),
Linux → NATIVE (OpenFOAM installed natively).
"""
function detect_backend()
    Sys.isapple() ? DOCKER : NATIVE
end

const DOCKER_CONTAINER = "openfoam2412"
const DOCKER_MOUNT_HOST = joinpath(homedir(), "OpenFOAM", "cases")
const DOCKER_MOUNT_CONTAINER = "/home/openfoam"

"""
    docker_case_path(host_path) → String

Translate a host path like `~/OpenFOAM/cases/airPower/...`
to the container path `/home/openfoam/airPower/...`.
"""
function docker_case_path(host_path::AbstractString)
    abs = abspath(host_path)
    if !startswith(abs, DOCKER_MOUNT_HOST)
        error("Path $abs is not under $DOCKER_MOUNT_HOST — cannot map to Docker container")
    end
    rel = abs[length(DOCKER_MOUNT_HOST)+2:end]
    return joinpath(DOCKER_MOUNT_CONTAINER, rel)
end

"""
    foam_exec(backend, case_path, cmd; verbose=true) → Bool

Run a single OpenFOAM command in `case_path`.
Returns true if the command succeeded.
"""
function foam_exec(backend::BackendType, case_path::AbstractString, cmd::AbstractString; verbose::Bool=true)
    if backend == DOCKER
        container_path = docker_case_path(case_path)
        full_cmd = `docker exec $(DOCKER_CONTAINER) bash -c "source /openfoam/bash.rc && cd $(container_path) && $(cmd)"`
    else
        full_cmd = `bash -c "cd $(abspath(case_path)) && source /usr/lib/openfoam/openfoam2412/etc/bashrc && $(cmd)"`
    end
    verbose && @info "Running: $cmd" case=basename(case_path)
    proc = run(ignorestatus(full_cmd), wait=true)
    if proc.exitcode != 0
        @error "Command failed (exit $(proc.exitcode)): $cmd"
        return false
    end
    return true
end

"""
    foam_script(backend, case_path, script; verbose=true) → Bool

Run an existing shell script (e.g. `run`, `clean`, `runPostProcess`) inside the case.
"""
function foam_script(backend::BackendType, case_path::AbstractString, script::AbstractString,
                     args::AbstractString=""; verbose::Bool=true)
    script_path = joinpath(case_path, script)
    if !isfile(script_path)
        @warn "Script not found: $script_path"
        return false
    end
    cmd = isempty(args) ? "bash $script" : "bash $script $args"
    foam_exec(backend, case_path, cmd; verbose)
end

# ── Wall modulation (smooth bump/depression) ─────────────────────────

"""
    _smoothstep(t, n)

Generalized smoothstep: S(0)=0, S(1)=1, S'(0)=S'(1)=0 for n≥2.
"""
_smoothstep(t, n) = t^n / (t^n + (1 - t)^n)

"""
    wall_bump(x; A, xStart, xPeak, xEnd, p, q)

Evaluate the wall modulation height at position x.
Uses piecewise sigmoidal smoothstep for C2 continuity (p,q ≥ 3).
"""
function wall_bump(x; A, xStart, xPeak, xEnd, p, q)
    (x <= xStart || x >= xEnd) && return 0.0
    if x <= xPeak
        t = (x - xStart) / (xPeak - xStart)
        return A * _smoothstep(t, p)
    else
        s = (x - xPeak) / (xEnd - xPeak)
        return A * (1.0 - _smoothstep(s, q))
    end
end

"""
    write_flat_plate_input_param(case_dir)

Generate `constant/inputParam` for the FlatPlateModule from the central
Julia inputs.  The file is auto-generated and should not be edited by hand.
"""
function write_flat_plate_input_param(case_dir::AbstractString)
    p = inp.DFP
    wm = p.wallModulation

    # Compute wall vertex y-displacements [mm] at the 7 block boundaries
    L = p.domainLength
    xverts = [0.0, 3.0/13.0*L, 7.0/26.0*L, 9.0/26.0*L, 5.0/13.0*L, 11.0/13.0*L, L]
    if wm.enabled && wm.mode == :single
        yverts = [wall_bump(xv; A=wm.A, xStart=wm.xStart, xPeak=wm.xPeak,
                            xEnd=wm.xEnd, p=wm.p, q=wm.q) * 1000.0  # m → mm
                  for xv in xverts]
    else
        yverts = zeros(7)
    end

    path = joinpath(case_dir, "constant", "inputParam")
    mkpath(dirname(path))
    open(path, "w") do io
        println(io, """/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                 |
| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\\\    /   O peration     | Version:  v2312                                 |
|   \\\\  /    A nd           | Website:  www.openfoam.com                      |
|    \\\\/     M anipulation  |                                                 |
\\*---------------------------------------------------------------------------*/
// AUTO-GENERATED by airPower orchestrator (inputs.jl) — do not edit
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      inputParam;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

//Boundaries information
Upinlet
{
//Domain geometry [m]
 domainLength  $(p.domainLength);
 domainHeight  $(p.domainHeight);

//Inflow parameters
 Uinf        $(p.Uinf);
 Winf        $(p.Winf);
 xInlet      $(p.xInlet);

//Top-boundary parameters (coefficient of polinomyal, Casacuberta et al, 2022)
 pa4         $(p.pa4);
 pa3         $(p.pa3);
 pa2         $(p.pa2);
 pa1         $(p.pa1);
 pa0         $(p.pa0);

//Fluid properties
 freeStreamViscosity   $(p.freeStreamViscosity);

//Grid resolution factors
 gridXfactor   $(p.gridXfactor);
 gridYfactor   $(p.gridYfactor);

//Output settings
 outputFormat          $(p.outputFormat);
 wallExtrapolation     $(p.wallExtrapolation ? "true" : "false");
}

//Wall modulation — vertex y-displacements [mm] at each block boundary
wallMod
{
 enabled  $(wm.enabled ? "true" : "false");
 y0       $(yverts[1]);
 y1       $(yverts[2]);
 y2       $(yverts[3]);
 y3       $(yverts[4]);
 y4       $(yverts[5]);
 y5       $(yverts[6]);
 y6       $(yverts[7]);
}

// ************************************************************************* //""")
    end
    @info "Generated constant/inputParam" case=basename(case_dir)

    # ── Write wall polyLine edges (system/wallEdges) ──
    edges_path = joinpath(case_dir, "constant", "wallEdges")
    N_KNOTS = 500  # knots per edge segment (only affects blockMesh, not solver)

    open(edges_path, "w") do io
        println(io, "// AUTO-GENERATED wall modulation edges — do not edit")
        if wm.enabled && wm.mode == :single
            # Wall edges: vertex pairs along the plate (z0 and z1 planes)
            # z0 plane: 0→1, 1→2, ..., 5→6  (vertices 0–6)
            # z1 plane: 21→22, ..., 26→27    (vertices 21–27)
            z0_mm = -1.0
            z1_mm =  1.0

            for (edge_i, (vi, vj)) in enumerate(zip(0:5, 1:6))
                xa = xverts[edge_i]
                xb = xverts[edge_i + 1]

                # Check if this edge overlaps with the bump
                if xb <= wm.xStart || xa >= wm.xEnd
                    continue  # entirely outside bump — straight edge is fine
                end

                # Generate knots: dense uniform within bump, sparse flat outside
                bump_lo = max(xa, wm.xStart)
                bump_hi = min(xb, wm.xEnd)

                knots_x = Float64[]
                # Flat before bump (few knots at y=0)
                if xa < bump_lo
                    for xk in range(xa, bump_lo, length=5)[2:end]
                        push!(knots_x, xk)
                    end
                end
                # Dense uniform within bump region
                for xk in range(bump_lo, bump_hi, length=N_KNOTS + 2)[2:end-1]
                    push!(knots_x, xk)
                end
                # Flat after bump (few knots at y=0)
                if bump_hi < xb
                    for xk in range(bump_hi, xb, length=5)[1:end-1]
                        push!(knots_x, xk)
                    end
                end

                knots_y = [wall_bump(xk; A=wm.A, xStart=wm.xStart, xPeak=wm.xPeak,
                                     xEnd=wm.xEnd, p=wm.p, q=wm.q) * 1000.0
                           for xk in knots_x]
                knots_x_mm = knots_x .* 1000.0
                n_total = length(knots_x)

                # z0 plane
                println(io, "    polyLine $vi $(vi+1)")
                println(io, "    (")
                for k in 1:n_total
                    @Printf.printf(io, "        (%.10g %.10g %.10g)\n",
                                   knots_x_mm[k], knots_y[k], z0_mm)
                end
                println(io, "    )")

                # z1 plane (same x,y knots, different z)
                vi_z1 = vi + 21
                vj_z1 = vj + 21
                println(io, "    polyLine $vi_z1 $vj_z1")
                println(io, "    (")
                for k in 1:n_total
                    @Printf.printf(io, "        (%.10g %.10g %.10g)\n",
                                   knots_x_mm[k], knots_y[k], z1_mm)
                end
                println(io, "    )")
            end
        end
    end
    @info "Generated system/wallEdges" case=basename(case_dir)

    # ── Write refinement dicts for bump region (system/topoSetDict, system/refineMeshDict) ──
    if wm.enabled && wm.mode == :single
        bumpL = wm.xEnd - wm.xStart
        H = p.domainHeight

        # Two refinement boxes:
        #   box1 (outer, 2×): margin = bumpL/2 on each side
        #   box2 (middle, 4×): margin = bumpL/4 on each side
        #   box3 (inner, 8×): exactly the bump region
        x1_lo = max(0.0, wm.xStart - bumpL / 2)
        x1_hi = min(L, wm.xEnd + bumpL / 2)
        x2_lo = max(0.0, wm.xStart - bumpL / 4)
        x2_hi = min(L, wm.xEnd + bumpL / 4)
        x3_lo = wm.xStart
        x3_hi = wm.xEnd

        # topoSetDict — defines three cellSets
        topo_path = joinpath(case_dir, "system", "topoSetDict")
        open(topo_path, "w") do io
            println(io, """FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      topoSetDict;
}

actions
(
    {
        name    refineBox1;
        type    cellSet;
        action  new;
        source  boxToCell;
        box     ($x1_lo -1 -1) ($x1_hi $(H+1) 1);
    }
    {
        name    refineBox2;
        type    cellSet;
        action  new;
        source  boxToCell;
        box     ($x2_lo -1 -1) ($x2_hi $(H+1) 1);
    }
    {
        name    refineBox3;
        type    cellSet;
        action  new;
        source  boxToCell;
        box     ($x3_lo -1 -1) ($x3_hi $(H+1) 1);
    }
);""")
        end

        # refineMeshDict — refine in x only
        refine_path = joinpath(case_dir, "system", "refineMeshDict")
        open(refine_path, "w") do io
            println(io, """FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      refineMeshDict;
}

set             refineBox1;

coordinateSystem global;

globalCoeffs
{
    tan1    (1 0 0);
    tan2    (0 1 0);
}

directions      (tan1);

useHexTopology  yes;

geometricCut    no;

writeMesh       no;""")
        end

        @info "Generated refinement dicts" case=basename(case_dir)
    end
end

const FOAM_HEADER = """/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                 |
| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\\\    /   O peration     | Version:  v2312                                 |
|   \\\\  /    A nd           | Website:  www.openfoam.com                      |
|    \\\\/     M anipulation  |                                                 |
\\*---------------------------------------------------------------------------*/
// AUTO-GENERATED by airPower orchestrator (inputs.jl) — do not edit"""

"""
    write_decompose_par_dict(case_dir, nProcs)

Generate `system/decomposeParDict` with the given number of processors.
"""
function write_decompose_par_dict(case_dir::AbstractString, nProcs::Int)
    path = joinpath(case_dir, "system", "decomposeParDict")
    mkpath(dirname(path))
    open(path, "w") do io
        println(io, """$(FOAM_HEADER)
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      decomposeParDict;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

numberOfSubdomains $(nProcs);

method          simple;

simpleCoeffs
{
    n               ( $(nProcs) 1 1 );
    delta           0.001;
}

// ************************************************************************* //""")
    end
end

"""
    write_tunnel_input_param(case_dir)

Generate `constant/inputParam` for TunnelCase from the central Julia inputs.
"""
function write_tunnel_input_param(case_dir::AbstractString)
    f = inp.TTCP.flow
    t = inp.TTCP.tunnel
    mm(x) = x * 1000.0   # m → mm
    path = joinpath(case_dir, "constant", "inputParam")
    mkpath(dirname(path))
    open(path, "w") do io
        println(io, """$(FOAM_HEADER)
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      inputParam;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

flowParam
{
//1.- Tunnel Geometrical Parameters

 //Basic geometry

 tunnelInletHalfHeight     $(mm(t.tunnelInletHalfHeight));        // [mm] (tunnel half height)

 tunnelOutletHalfHeight    $(mm(t.tunnelOutletHalfHeight));        // [mm]

 tunnelLength       $(mm(t.tunnelLength));         //[mm]

//2.- Grid Discretization Parameters

 //Streamwise partitions
 Nx $(t.Nx);                             // [-]

 //Wall-normal partitions
 Ny $(t.Ny);                              // [-]

//3.- Flow Parameters (m as dimensional units)

 freeStreamVelocityStreamwise    $(f.freeStreamVelocityStreamwise);       //[ms^1]

 freeStreamVelocitySpanwise     $(f.freeStreamVelocitySpanwise);        //[ms^1]

 freeStreamViscosity   $(f.freeStreamViscosity);    //[m^2s^1]

//4.- Turbulence Parameters

 turbulenceIntensity   $(t.turbulenceIntensity);        //[-]
 turbLengthScale       $(t.turbLengthScale);         //[m]

//5.- BSpline Control Points [mm]

 xcp1 $(mm(t.xcp1));
 ycp1 $(mm(t.ycp1));

 xcp2 $(mm(t.xcp2));
 ycp2 $(mm(t.ycp2));

 xcp3 $(mm(t.xcp3));
 ycp3 $(mm(t.ycp3));
}

// ************************************************************************* //""")
    end
    write_decompose_par_dict(case_dir, inp.TTCP.nProcs)
    @info "Generated constant/inputParam" case=basename(case_dir)
end

"""
    write_airfoil_le_input_param(case_dir)

Generate `constant/inputParam` for AirfoilLECase from the central Julia inputs.
(Grid/domain parameters in `system/inputDomain` are no longer needed —
 `generateGrid.jl` reads `inputs.jl` directly.)
"""
function write_airfoil_le_input_param(case_dir::AbstractString)
    f = inp.TTCP.flow
    t = inp.TTCP.tunnel
    a = inp.TTCP.airfoilLE
    mm(x) = x * 1000.0   # m → mm

    # Load upper-surface airfoil data from the .dat file
    airfoil_dat = joinpath(dirname(dirname(case_dir)),
                           "..", "InputOutput", "AirfoilGeometryData", t.airfoilFile)
    xi_up, eta_up = load_airfoil_upper(airfoil_dat)

    # ── constant/inputParam ──────────────────────────────────────────────
    path_ip = joinpath(case_dir, "constant", "inputParam")
    mkpath(dirname(path_ip))
    open(path_ip, "w") do io
        println(io, """$(FOAM_HEADER)
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      inputParam;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

//Boundaries information
Upinlet
{
//Fluid properties
 freeStreamViscosity            $(f.freeStreamViscosity);              //[m^2s^1]
 freeStreamVelocityStreamwise   $(f.freeStreamVelocityStreamwise);    //[ms^1]
 freeStreamVelocitySpanwise     $(f.freeStreamVelocitySpanwise);      //[ms^1]

//Output settings
 outputFormat          $(a.outputFormat);      // csv | binary
 wallExtrapolation     $(a.wallExtrapolation ? "true" : "false");

//Export region settings
 exportMode            $(a.exportMode);  // full | partial
 xiInlet               $(a.xiInlet);     // chord fraction for inlet boundary (x/c)
 xiOutlet              $(a.xiOutlet);     // chord fraction for outlet boundary (x/c)
 exportHeight          $(mm(a.exportHeight));       // wall-normal distance from surface [mm]

//Airfoil geometry
 chord                 $(mm(t.chord));      // [mm]
 alphaDeg              $(t.alphaDeg);     // [deg]
 xCenter               $(mm(t.xCenter));     // [mm]
 yCenter               $(mm(t.yCenter));     // [mm]

//Upper-surface airfoil coordinates (xi/c, eta/c), LE to TE
 airfoilXi             $(length(xi_up))($(join(string.(xi_up), " ")));
 airfoilEta            $(length(eta_up))($(join(string.(eta_up), " ")));
}

// ************************************************************************* //""")
    end
    write_decompose_par_dict(case_dir, inp.TTCP.nProcs)
    @info "Generated constant/inputParam" case=basename(case_dir)
end

"""
    load_airfoil_upper(filepath) → (xi, eta)

Read an airfoil .dat file (tab/space-separated x/c, y/c columns, full
contour TE→LE→TE) and return the upper-surface points sorted LE→TE.
"""
function load_airfoil_upper(filepath::AbstractString)
    xi_all = Float64[]
    eta_all = Float64[]
    for line in eachline(filepath)
        line = strip(line)
        isempty(line) && continue
        parts = split(line)
        length(parts) >= 2 || continue
        x = tryparse(Float64, parts[1])
        y = tryparse(Float64, parts[2])
        (x === nothing || y === nothing) && continue
        push!(xi_all, x)
        push!(eta_all, y)
    end

    mask = eta_all .>= 0.0
    xi_up  = xi_all[mask]
    eta_up = eta_all[mask]

    perm = sortperm(xi_up)
    xi_up  = xi_up[perm]
    eta_up = eta_up[perm]

    keep = [true; [!(xi_up[i] == xi_up[i-1] && eta_up[i] == eta_up[i-1]) for i in 2:length(xi_up)]]
    return xi_up[keep], eta_up[keep]
end

"""
    run_julia_subprocess(script_path; dir, args) → Bool

Run a Julia script as a subprocess (isolated from our module scope).
"""
function run_julia_subprocess(script_path::AbstractString;
                              dir::AbstractString=dirname(script_path),
                              args::Vector{String}=String[])
    abs_script = abspath(script_path)
    if !isfile(abs_script)
        @warn "Julia script not found: $abs_script"
        return false
    end
    @info "Running Julia subprocess: $(basename(abs_script))"
    cmd = `julia $abs_script $args`
    proc = run(Cmd(cmd; dir), wait=true)
    return proc.exitcode == 0
end
